name: Clean Living 365
favicon: null
layout_spectrum: 0.624539139913395
typography_spectrum: 0.06547790952026844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6072964302729815
  lightness: 0.9287652224302292
  saturation: 0.34075911180116236
  rhythmicContrast: 0.6744115890469402
purpose: []
